language: node_js
node_js:
    - "10"
dist: trusty
addons:
    chrome: beta
sudo: required
branches:
    only:
        - master
before_script:
    - npm install -g @angular/cli
    -
script:
    - npm run lint
    - npm run test -- --no-watch
